export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_ACTIVITY = "GET_USER_ACTIVITY";
export const LOAD_ARTICLES = "LOAD_ARTICLES";
export const GET_ARTICLE = "GET_ARTICLE";

